"""empty message

Revision ID: 2d0b5f98bc51
Revises: 
Create Date: 2018-05-01 00:07:55.542031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d0b5f98bc51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('gender', mysql.TINYINT(), nullable=False),
    sa.Column('state', mysql.TINYINT(), nullable=False),
    sa.Column('active', mysql.TINYINT(), nullable=False),
    sa.Column('manager', mysql.TINYINT(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_info',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('sign', mysql.TEXT(), nullable=False),
    sa.Column('intro', mysql.TEXT(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    op.drop_table('user')
    # ### end Alembic commands ###
