"""empty message

Revision ID: 534e132d5414
Revises: 
Create Date: 2018-05-05 23:41:55.123361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '534e132d5414'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('gender', mysql.TINYINT(), nullable=False),
    sa.Column('state', mysql.TINYINT(), nullable=False),
    sa.Column('active', mysql.TINYINT(), nullable=False),
    sa.Column('manager', mysql.TINYINT(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blog',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('subtitle', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('intro', mysql.TEXT(), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('logo', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_create_time'), 'blog', ['create_time'], unique=False)
    op.create_index(op.f('ix_blog_title'), 'blog', ['title'], unique=False)
    op.create_index(op.f('ix_blog_update_time'), 'blog', ['update_time'], unique=False)
    op.create_table('user_info',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('sign', mysql.TEXT(), nullable=False),
    sa.Column('intro', mysql.TEXT(), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('avatar', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('state', mysql.TINYINT(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    op.drop_index(op.f('ix_blog_update_time'), table_name='blog')
    op.drop_index(op.f('ix_blog_title'), table_name='blog')
    op.drop_index(op.f('ix_blog_create_time'), table_name='blog')
    op.drop_table('blog')
    op.drop_table('user')
    # ### end Alembic commands ###
